### ISSUE TITLE
Feature: navigation buttons in the Rebound Hub title bar

### ISSUE THREAD

**Issue by IviriusMain** [IviriusCommunity/Rebound#52]
### 📄 Description

Add back, forward, and refresh buttons to the Rebound Hub title bar for easier navigation

**Comment by Lamparter** [comment]
I don't think there's much point in this, since there's not really much navigation in Rebound Hub anyway. Navigation styles are more important in apps like FluentHub or Files because of the fact that there are near hundreds of views, but Rebound Hub is just a demo of Rebound 11 rather than something that requires proper navigation.

**Comment by IviriusMain** [comment]
So just keep it in the Control Panel then?

**Comment by Lamparter** [comment]
Yes.
